### PR TITLE
Modern badges

### PR DESCRIPTION
**Pull request by ZeroX-DG**
This PR add modern version for all badges.

[From Vietnam with <3](https://webuild.community)

[Brew in Vietnam](https://webuild.community)

[Made in Vietnam](https://webuild.community)

[By Vietnamese](https://webuild.community)

[Member of webuild](https://webuild.community)

### CODE REVIEW

**Comment by huytd** [comment]
👍

**Review by huytd — APPROVED** [review]

**Review by runlevel5 — APPROVED** [review]

**Comment by runlevel5** [comment]
@ZeroX-DG can we update the README with these new styles too? TIA

**Comment by ZeroX-DG** [comment]
Yup for sure :+1:

**Comment by ZeroX-DG** [comment]
@runlevel5 done :+1:

**Pull request merged**
